server:
  port: 8080


#  eureka.client.service-url.defaultZone=http://localhost:8761/eureka
#
#  eureka.client.register-with-eureka=true
#  eureka.client.fetch-registry=true

#eureka.client.service-url.defaultZone=http://192.168.0.7:8761/eureka
#eureka.instance.preferIpAddress=true
#eureka.instance.hostname=192.168.0.7


#eureka:
#  client:
#    service-url:
#      defaultZone: http://ip172-18-0-13-c1nmrc8h550g00dqjmu0-8761.direct.labs.play-with-docker.com/eureka
#    register-with-eureka: true
##    fetch-registry: true

spring:
  profiles:
    active: dev
  application:
    name: bcp-shopvintage-bidders
  config:
    import: optional:configserver:http://ip172-18-0-13-c1nmrc8h550g00dqjmu0-8888.direct.labs.play-with-docker.com
    #    import: optional:configserver:http://localhost:8888

#
#  datasource:
#    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
#    url: jdbc:sqlserver://bootcamp-server-bd.database.windows.net;database=shopvintagebd;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
#    username: bootcampuser@bootcamp-server-bd
#    password: Bootcamp2021
#
#  jpa:
#    show-sql: true
#    properties:
#      hibernate:
#        dialect: org.hibernate.dialect.SQLServer2012Dialect
#    hibernate:
#      naming:
#        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl
#        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

